Repository Dev-One-Project/ONF-client, pull requests merged in 2023-01, with the labels that each got.

#192 :zap: (notice) MODIFY: 공지사항 UPDATE
  src/commons/store/index.ts
  src/components/commons/modal/noticeModal.tsx
  src/components/commons/notice/list/list.presenterDetail.tsx
  src/components/commons/notice/write/modules/editor.tsx
  src/components/commons/notice/write/write.container.tsx
  src/components/commons/notice/write/write.presenter.tsx
  src/components/commons/notice/write/write.queries.ts
  src/components/commons/notice/write/write.types.ts
Labels: modify

#195 :sparkles: (Calendar): FEATURE: 월 이동기능 추가 및 스타일링
  src/components/commons/calendar/calendarSource/calendar.container.tsx
  src/components/commons/calendar/calendarSource/calendar.presenter.tsx
  src/components/commons/calendar/calendarSource/calendar.styles.ts
  src/components/commons/calendar/calendarSource/calendar.types.ts
Labels: feature

#196 :sparkles: (notice) FEATURE: 공지사항 리스트 페이지네이션 #193
  src/components/commons/modal/noticeModal.tsx
  src/components/commons/notice/list/list.container.tsx
  src/components/commons/notice/list/list.presenter.tsx
  src/components/commons/notice/list/list.styles.ts
  src/components/commons/notice/list/list.types.ts
  src/components/commons/pagination/pagination01.tsx
Labels: feature

#199 :sparkles: (memberAPI): FEATURE: create/update/delete Member API 연결
  src/components/commons/input/select01.tsx
  src/components/units/admin/manage/formsInModal/common/footer.tsx
  src/components/units/admin/manage/formsInModal/common/form.types.ts
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/member/member.queries.ts
  src/components/units/admin/manage/formsInModal/member/member.tsx
  src/components/units/admin/manage/manage.container.tsx
  src/components/units/admin/manage/manage.presenter.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/manage.types.ts
  src/components/units/admin/manage/scrollableTable/index.tsx
Labels: feature

#201 :bug: (select01): FIX: select01 버그 픽스
  src/components/commons/input/select01.tsx
Labels: fix

#202 :sparkles: (attendancesModal): FEATURE: 출퇴근기록 관리 목록형 모달창
  src/commons/styles/globalStyles.ts
  src/commons/types/generated/types.ts
  src/commons/utils/getDate.ts
  src/components/commons/input/select02.tsx
  src/components/commons/layoutAdmin/index.tsx
  src/components/units/admin/attendances/list/attendancesList.container.tsx
  src/components/units/admin/attendances/list/attendancesList.presenter.tsx
  src/components/units/admin/attendances/list/attendancesList.queries.ts
  src/components/units/admin/attendances/list/attendancesList.styles.ts
  src/components/units/admin/attendances/list/attendancesList.types.ts
  src/components/units/admin/attendances/modules/addAttendances.tsx
  src/components/units/admin/attendances/modules/attendancesInput.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.styles.ts
  src/components/units/admin/leaves/leaves.container.tsx
  src/components/units/admin/leaves/leaves.presenter.tsx
  src/components/units/admin/leaves/leaves.types.ts
  src/components/units/layoutAdmin/header/header.presenter.tsx
Labels: feature

#210 :zap: (notice) MODIFY: 공지사항 내용 이미지 업로드 관련 #197
  src/components/commons/notice/write/modules/editor.tsx
  src/components/commons/notice/write/write.container.tsx
  src/components/commons/notice/write/write.queries.ts
Labels: modify

#212 :zap: (adminRequest) MODIFY: 관리자 요청내역 Select01 수정 #211
  src/components/units/admin/requests/request.presenter.tsx
Labels: modify

#213 :sparkles: (Calendar): FEATURE: 공통컴포넌트 캘린더 기능 구현 (유저 요청 기능 구현 포함)
  src/components/commons/calendar/calendar.tsx
  src/components/commons/calendar/calendarSource/calendar.container.tsx
  src/components/commons/calendar/calendarSource/calendar.presenter.tsx
  src/components/commons/calendar/calendarSource/calendar.types.ts
  src/components/units/user/createRequest/createReq.container.tsx
  src/components/units/user/createRequest/createReq.presenter.tsx
  src/components/units/user/createRequest/createReq.types.ts
Labels: feature

#214 :sparkles: (fetchOrganization): FEATURE: 지점 fetch API 연결
  pages/admin/manage/organization/index.tsx
  pages/admin/manage/role-category/index.tsx
  src/components/units/admin/manage/formsInModal/common/form.types.ts
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/member/member.tsx
  src/components/units/admin/manage/formsInModal/oraganization/oranization.presenter.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organization.container.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/scrollableTable/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/members/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/organization/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/roleCategory/index.tsx
  src/components/units/auth/login/login.container.tsx
Labels: feature

#217 :sparkles: (Scheduler): FEATURE: 근무일정 생성 모달 추가
  src/commons/types/generated/types.ts
  src/components/commons/calendar/calendar.tsx
  src/components/commons/calendar/calendarSource/calendar.container.tsx
  src/components/commons/calendar/calendarSource/calendar.presenter.tsx
  src/components/commons/calendar/calendarSource/calendar.types.ts
  src/components/commons/input/select05.tsx
  src/components/commons/layoutuser/layout.types.tsx
  src/components/units/admin/scheduler/calendar/schedulerCalendar.container.tsx
  src/components/units/admin/scheduler/calendar/schedulerCalendar.presenter.tsx
  src/components/units/admin/scheduler/calendar/schedulerCalendar.queries.ts
  src/components/units/admin/scheduler/calendar/schedulerCalendar.styles.ts
  src/components/units/admin/scheduler/calendar/schedulerCalendar.types.ts
  src/components/units/admin/scheduler/list/schedulerList.container.tsx
  src/components/units/admin/scheduler/list/schedulerList.presenter.tsx
  src/components/units/admin/scheduler/list/schedulerList.queries.ts
  src/components/units/admin/scheduler/list/schedulerList.styles.ts
  src/components/units/admin/scheduler/list/schedulerList.types.ts
  src/components/units/admin/scheduler/modules/createModal/createModal.quries.ts
  src/components/units/admin/scheduler/modules/createModal/createModal.tsx
  src/components/units/user/attendances/attendances.types.ts
Labels: feature

#219 :zap: (join): MODIFY: 회원가입 수정된 API 적용 #168
  src/components/commons/layoutuser/header/index.tsx
  src/components/units/auth/join/join.adminModal.tsx
  src/components/units/auth/join/join.container.tsx
  src/components/units/auth/join/join.employeeModal.tsx
  src/components/units/auth/join/join.presenter.tsx
  src/components/units/auth/join/join.queries.ts
  src/components/units/auth/join/join.styles.ts
  src/components/units/auth/join/join.types.ts
Labels: modify

#220 :sparkles: (fetchSchedules): FEATURE: 근무일정 유형/템플릿, 휴가 유형 fetch API 연결
  pages/admin/manage/leave-types/index.tsx
  pages/admin/manage/schedule-category/index.tsx
  pages/admin/manage/schedule-template/index.tsx
  pages/admin/manage/shift-template/index.tsx
  pages/admin/manage/shift-types/index.tsx
  pages/admin/manage/vacation-category/index.tsx
  pages/admin/manage/wages/index.tsx
  src/components/commons/layoutuser/layout.styles.ts
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/member/member.tsx
  src/components/units/admin/manage/formsInModal/scheduleCategory.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate.tsx
  src/components/units/admin/manage/manage.container.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/manage.types.ts
  src/components/units/admin/manage/manageSidebar/index.tsx
  src/components/units/admin/manage/scrollableTable/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/organization/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/scheduleCategory/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/scheduleTemplate/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/vacationCategory/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/wages/index.tsx
  src/components/units/user/attendances/attendances.container.tsx
  src/components/units/user/attendances/attendances.presenter.tsx
  src/components/units/user/attendances/attendances.queries.ts
  src/components/units/user/attendances/attendances.styles.ts
Labels: feature

#224 :sparkles: (attendancesCalendar): FEATURE: 출퇴근기록 관리 달력형 세부 퍼블리싱
  src/commons/types/generated/types.ts
  src/commons/utils/getDate.ts
  src/components/commons/input/select02.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.container.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.presenter.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.queries.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.styles.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.types.ts
  src/components/units/admin/attendances/list/attendancesList.container.tsx
  src/components/units/admin/attendances/list/attendancesList.presenter.tsx
  src/components/units/admin/attendances/list/attendancesList.queries.ts
  src/components/units/admin/attendances/list/attendancesList.styles.ts
  src/components/units/admin/attendances/list/attendancesList.types.ts
  src/components/units/admin/attendances/modules/addAttendances.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.queries.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.types.ts
  src/components/units/admin/leaveAccruals/modules/addLeaveAccruals.tsx
  src/components/units/admin/leaveAccruals/modules/employeeOptionalFetch.tsx
  src/components/units/admin/leaveAccruals/modules/listOptionalFetch.tsx
  src/components/units/admin/leaves/leaves.container.tsx
  src/components/units/admin/leaves/leaves.presenter.tsx
  src/components/units/admin/leaves/leaves.types.ts
  src/components/units/layoutAdmin/sidebar/sidebar.presenter.tsx
  src/components/units/layoutAdmin/sidebar/sidebar.styles.ts
Labels: feature

#226 :sparkles: (fetchMemberWorkCheck): FEATURE: 출퇴근기록(유저) fetch API 연결
  src/commons/store/index.ts
  src/components/commons/layoutUser/sidebar/attendances.tsx
  src/components/units/admin/manage/manage.presenter.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/scrollableTable/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/vacationCategory/index.tsx
  src/components/units/auth/login/login.container.tsx
  src/components/units/user/attendances/attendances.container.tsx
  src/components/units/user/attendances/attendances.presenter.tsx
  src/components/units/user/attendances/attendances.queries.ts
  src/components/units/user/attendances/attendances.styles.ts
  src/components/units/user/attendances/attendances.types.ts
Labels: feature

#227 :sparkles: (leave): FEATURE: 휴가목록 api 연결
  src/commons/types/generated/types.ts
  src/commons/utils/getDate.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.styles.ts
  src/components/units/admin/attendances/list/attendancesList.container.tsx
  src/components/units/admin/attendances/list/attendancesList.presenter.tsx
  src/components/units/admin/attendances/list/attendancesList.styles.ts
  src/components/units/admin/attendances/list/attendancesList.types.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.queries.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.styles.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.types.ts
  src/components/units/admin/leaveAccruals/modules/addLeaveAccruals.tsx
  src/components/units/admin/leaves/leaves.container.tsx
  src/components/units/admin/leaves/leaves.presenter.tsx
  src/components/units/admin/leaves/leaves.queries.ts
  src/components/units/admin/leaves/leaves.styles.ts
  src/components/units/admin/leaves/leaves.types.ts
  src/components/units/admin/leaves/modules/leaveOptionalFetch.tsx
  src/components/units/layoutAdmin/sidebar/sidebar.styles.ts
Labels: feature

#229 :zap: (Switch01): MODIFY: 스위치01 수정
  public/icon_logo.png
  src/commons/styles/styleSet.ts
  src/components/commons/layoutUser/index.tsx
  src/components/commons/layoutUser/layout.queries.ts
  src/components/commons/layoutUser/layout.types.ts
  src/components/commons/switch/switch01.tsx
  src/components/units/auth/join/join.container.tsx
  src/components/units/auth/join/join.presenter.tsx
  src/components/units/auth/login/login.presenter.tsx
  src/components/units/layoutAdmin/header/header.presenter.tsx
  src/components/units/user/attendances/attendances.presenter.tsx
  src/components/units/user/attendances/attendances.styles.ts
  src/components/units/user/requests/requests.styles.ts
Labels: modify

#231 :alien: (fetchVacationCategories): MODIFY: fetchVacationCategories API 스펙 변경에 따른 수정
  pages/admin/manage/vacation-category/index.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/manage.types.ts
  src/components/units/admin/manage/scrollableTable/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/vacationCategory/index.tsx
Labels: modify

#234 :sparkles: (mainIndex): FEATURE: 메인페이지 제작 #232
  pages/_app.tsx
  pages/index.tsx
  public/icon_logo.png
  src/components/commons/input/input01.tsx
  src/components/commons/layoutUser/index.tsx
  src/components/commons/layoutUser/layout.types.ts
  src/components/commons/layoutuser/header/index.tsx
  src/components/commons/layoutuser/layout.styles.ts
  src/components/commons/layoutuser/layout.types.tsx
  src/components/units/layoutAdmin/header/header.presenter.tsx
  src/components/units/layoutAdmin/header/header.styles.tsx
  src/components/units/user/attendances/attendances.presenter.tsx
  src/components/units/user/requests/requests.styles.ts
Labels: feature

#235 :sparkles: (UserSchedule): FEATURE: migrate schedule apis
  src/commons/types/generated/types.ts
  src/components/commons/layoutUser/index.tsx
  src/components/units/admin/scheduler/list/schedulerList.presenter.tsx
  src/components/units/user/schedule/schedule.container.tsx
  src/components/units/user/schedule/schedule.presenter.tsx
  src/components/units/user/schedule/schedule.quries.ts
  src/components/units/user/schedule/schedule.style.ts
  src/components/units/user/schedule/schedule.types.ts
Labels: feature

#236 :sparkles: (attendanceCalendar): FEATURE: 출퇴근기록 달력형 fetch
  src/components/units/admin/attendances/calendar/attendancesCalendar.presenter.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.queries.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.styles.ts
  src/components/units/admin/attendances/list/attendancesList.presenter.tsx
  src/components/units/admin/attendances/list/attendancesList.queries.ts
  src/components/units/admin/attendances/modules/addAttendances.tsx
  src/components/units/admin/leaveAccruals/modules/addLeaveAccruals.tsx
  src/components/units/admin/leaveAccruals/modules/employeeOptionalFetch.tsx
  src/components/units/admin/leaveAccruals/modules/listOptionalFetch.tsx
  src/components/units/admin/leaves/modules/leaveOptionalFetch.tsx
Labels: feature

#238 :zap: (adminHome) MODIFY: 관리자 홈 수정 #221
  src/components/commons/modal/noticeModal.tsx
  src/components/commons/notice/list/list.presenterDetail.tsx
  src/components/commons/notice/list/list.queries.ts
  src/components/commons/notice/write/modules/editor.tsx
  src/components/units/admin/home/home.container.tsx
  src/components/units/admin/home/home.presenter.tsx
  src/components/units/admin/home/home.queries.ts
  src/components/units/admin/home/home.styles.ts
  src/components/units/admin/home/home.types.ts
Labels: modify

#240 :zap: (noticeModal) MODIFY: 공지사항 모달 리스트 수정 #239
  src/components/commons/modal/noticeModal.tsx
  src/components/commons/notice/list/list.container.tsx
  src/components/commons/notice/list/list.presenterDetail.tsx
  src/components/commons/notice/list/list.styles.ts
Labels: modify

#244 :sparkles: (select01): FEATURE: select01 단일 선택 기능 추가
  src/components/commons/input/select01.tsx
  src/components/commons/inputLabel.tsx
  src/components/units/admin/manage/formsInModal/member/member.tsx
Labels: feature

#242 :sparkles: (workInfo): FEATURE: 근로 정보 fetch API 연결
  pages/admin/manage/wages/index.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/manage.types.ts
  src/components/units/admin/manage/scrollableTable/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/wages/index.tsx
Labels: feature

#251 :sparkles: (adminManageMember): FEATURE: 어드민 관리 직원 create API 연결
  pages/admin/manage/members/index.tsx
  src/components/commons/input/select01.tsx
  src/components/units/admin/manage/formsInModal/common/form.types.ts
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/member/member.tsx
  src/components/units/admin/manage/formsInModal/member/memberForm.container.tsx
  src/components/units/admin/manage/formsInModal/member/memberForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/member/memberForm.queries.ts
  src/components/units/admin/manage/formsInModal/member/memberForm.styles.ts
  src/components/units/admin/manage/formsInModal/member/memberForm.types.ts
  src/components/units/admin/manage/scrollableTable/rowDataCells/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/members/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/organization/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/roleCategory/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/scheduleCategory/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/scheduleTemplate/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/vacationCategory/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/wages/index.tsx
Labels: feature

#256 :sparkles: (switch01): FEATURE: switch01 퇴근하기 기능 적용 #245
  src/commons/accessToken.tsx
  src/commons/types/generated/types.ts
  src/components/commons/layoutUser/header/index.tsx
  src/components/commons/layoutUser/layout.queries.ts
  src/components/commons/layoutUser/layout.types.ts
  src/components/commons/switch/switch01.tsx
  src/components/units/auth/join/join.presenter.tsx
  src/components/units/auth/login/login.container.tsx
  src/components/units/auth/login/login.presenter.tsx
Labels: feature

#259 :sparkles: (main): STYLE: 메인페이지 디자인 & 퍼블리싱 #257
  pages/index.tsx
  public/main/img_on&off.png
  public/main/main-obj.png
  public/main/sub-obj2.png
  src/components/commons/layoutUser/header/index.tsx
  src/components/commons/layoutUser/layout.styles.ts
Labels: style

#263 :sparkles: (adminManageOrganization): FEATURE: 어드민 관리(지점) create API 연결
  src/components/units/admin/manage/formsInModal/attendanceLocation/index.tsx
  src/components/units/admin/manage/formsInModal/common/inputLabel.tsx
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/leaveTypes.tsx
  src/components/units/admin/manage/formsInModal/member/memberForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/oraganization/kakaoMapLauncher.tsx
  src/components/units/admin/manage/formsInModal/oraganization/oranization.presenter.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organization.container.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.container.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.queries.ts
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.styles.ts
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.types.ts
  src/components/units/admin/manage/formsInModal/roleCategory.tsx
  src/components/units/admin/manage/formsInModal/scheduleCategory.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate.tsx
  src/components/units/admin/manage/formsInModal/wages/basicInfo.tsx
  src/components/units/admin/manage/manage.container.tsx
  src/components/units/admin/manage/manage.presenter.tsx
  src/components/units/admin/manage/manage.queries.ts
  src/components/units/admin/manage/manageSidebar/index.tsx
  src/components/units/admin/manage/scrollableTable/rowDataCells/organization/index.tsx
Labels: feature

#265 :sparkles: (adminManageRoleCategory): FEATURE: 어드민 관리(직무) create API 연결
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/member/memberForm.container.tsx
  src/components/units/admin/manage/formsInModal/oraganization/organizationForm.container.tsx
  src/components/units/admin/manage/formsInModal/roleCategory.tsx
  src/components/units/admin/manage/formsInModal/roleCategory/roleCategoryForm.container.tsx
  src/components/units/admin/manage/formsInModal/roleCategory/roleCategoryForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/roleCategory/roleCategoryForm.queries.ts
  src/components/units/admin/manage/formsInModal/roleCategory/roleCategoryForm.styles.ts
  src/components/units/admin/manage/formsInModal/roleCategory/roleCategoryForm.types.ts
Labels: feature

#260 :zap: (AttendancesCalendar): MODIFY: 출퇴근기록 달력형 수정
  src/commons/utils/getDate.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.container.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.presenter.tsx
  src/components/units/admin/attendances/calendar/attendancesCalendar.queries.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.styles.ts
  src/components/units/admin/attendances/calendar/attendancesCalendar.types.ts
  src/components/units/admin/attendances/modules/addAttendances.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.queries.ts
  src/components/units/admin/leaveAccruals/modules/employeeOptionalFetch.tsx
  src/components/units/admin/leaveAccruals/modules/listOptionalFetch.tsx
Labels: modify

#262 :zap: (adminHeader): MODIFY: 관리자 Layout Header 추가 기능
  src/commons/types/generated/types.ts
  src/components/commons/hooks/useAuth.ts
  src/components/commons/layoutUser/layout.queries.ts
  src/components/units/layoutAdmin/header/header.container.tsx
  src/components/units/layoutAdmin/header/header.presenter.tsx
  src/components/units/layoutAdmin/header/header.styles.ts
  src/components/units/layoutAdmin/header/header.types.ts
Labels: modify

#267 :sparkles: (adminManageScheduleCategory): FEATURE: 어드민 관리(근무일정 유형) cr…
  src/components/commons/button/btn01.tsx
  src/components/units/admin/manage/formsInModal/common/footer.tsx
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/scheduleCategory/scheduleCategoryForm.container.tsx
  src/components/units/admin/manage/formsInModal/scheduleCategory/scheduleCategoryForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/scheduleCategory/scheduleCategoryForm.queries.ts
  src/components/units/admin/manage/formsInModal/scheduleCategory/scheduleCategoryForm.styles.ts
  src/components/units/admin/manage/formsInModal/scheduleCategory/scheduleCategoryForm.types.ts
Labels: feature

#273 :zap: (loginAuth): Modify: LoginAuth 수정 #272
  pages/index.tsx
  src/components/commons/hooks/loginAuth.ts
  src/components/units/auth/login/login.presenter.tsx
Labels: modify

#275 :sparkles: (adminManageScheduleTemplate): FEATURE: 어드민 관리(근무일정 템플릿) create API 연결
  pages/admin/manage/schedule-category/index.tsx
  pages/admin/manage/schedule-template/index.tsx
  src/components/commons/input/select01.tsx
  src/components/units/admin/manage/formsInModal/common/form.types.ts
  src/components/units/admin/manage/formsInModal/common/inputLabel.tsx
  src/components/units/admin/manage/formsInModal/index.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate/scheduleTemplateForm.container.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate/scheduleTemplateForm.presenter.tsx
  src/components/units/admin/manage/formsInModal/scheduleTemplate/scheduleTemplateForm.queries.ts
  src/components/units/admin/manage/formsInModal/scheduleTemplate/scheduleTemplateForm.styles.ts
  src/components/units/admin/manage/formsInModal/scheduleTemplate/scheduleTemplateForm.types.ts
  src/components/units/admin/manage/manage.queries.ts
Labels: feature

#283 :sparkles: (sidebar): user 사이드바 기능연결 #274
  pages/index.tsx
  src/components/commons/calendar/calendarSource/calendar.presenter.tsx
  src/components/commons/calendar/calendarSource/calendar.styles.ts
  src/components/commons/layoutUser/layout.queries.ts
  src/components/units/auth/join/join.presenter.tsx
  src/components/units/user/createRequest/createReq.presenter.tsx
  src/components/units/user/createRequest/createReq.styles.ts
  src/components/units/user/schedule/schedule.presenter.tsx
  src/components/units/user/schedule/schedule.style.ts
Labels: feature

#286 :zap: (leaveAccrualsList): MODIFY: 휴가 발생- 목록 단일 update, delete
  src/components/commons/input/select02.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/modules/checkedEditLeaveAccruals.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.queries.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.types.tsx
Labels: modify

#288 :zap: (leaveAccrualsMember): MODIFY: 휴가 발생- 직원 직원별 조회, update, delete
  src/components/units/admin/leaveAccruals/leaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/leaveAccruals.queries.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.styles.ts
  src/components/units/admin/leaveAccruals/leaveAccruals.types.ts
  src/components/units/admin/leaveAccruals/modules/addLeaveAccruals.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/modules/edit/editLeaveAccruals.types.tsx
  src/components/units/admin/leaveAccruals/modules/employeeOptionalFetch.tsx
  src/components/units/admin/leaveAccruals/modules/memberEdit/memberEditLeaveAccruals.container.tsx
  src/components/units/admin/leaveAccruals/modules/memberEdit/memberEditLeaveAccruals.presenter.tsx
  src/components/units/admin/leaveAccruals/modules/memberEdit/memberEditLeaveAccruals.queries.ts
  src/components/units/admin/leaveAccruals/modules/memberEdit/memberEditLeaveAccruals.styles.ts
  src/components/units/admin/leaveAccruals/modules/memberEdit/memberEditLeaveAccruals.types.ts
Labels: modify

#290 ⚡ (createAccount): MODIFY: 백엔드 api 수정에 따른 gql 수정
  src/components/units/auth/join/join.queries.ts
Labels: modify
